name: riverpod_zap
description: Support for `riverpod` in zap components.
version: 1.0.0

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  riverpod: ^2.0.0-dev.0
  rxdart: ^0.27.0
  zap:
  # Note: Even when the root build is happening from another package, zap_dev
  # should be applied to this one.
  zap_dev:

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0


dependency_overrides:
  zap:
    path: ../zap
  zap_dev:
    path: ../zap_dev
