name: riverpod_zap
description: Support for `riverpod` in zap components.
version: 0.1.1
homepage: https://simonbinder.eu/zap/

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  riverpod: ^2.0.0
  zap: ^0.2.0
  # Note: Even when the root build is happening from another package, zap_dev
  # should be applied to this one.
  zap_dev: ^0.2.0

dev_dependencies:
  build_runner: ^2.0.0
  build_test: ^2.1.5
  build_web_compilers: ^3.0.0
  lints: ^1.0.0
  test: ^1.16.0

dependency_overrides:
  zap:
    path: ../zap
  zap_dev:
    path: ../zap_dev
