name: material_zap_example
description: Port of material web components to zap
publish_to: none

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  zap:
  zap_dev:
  material_zap:

dev_dependencies:
  build_runner: ^2.1.7
  build_web_compilers: ^3.2.2

dependency_overrides:
  material_zap:
    path: ../
  zap:
    path: ../../zap
  zap_dev:
    path: ../../zap_dev
