builders:
  zap_dev:
    import: 'package:zap_dev/builders.dart'
    builder_factories: ["preparing", "api", "zapBuilder"]
    auto_apply: dependents
    build_to: cache
    applies_builders: [":zap_cleanup"]
    defaults:
      dev_options:
        dev: true
      release_options:
        dev: false
    build_extensions:
      ".zap":
        - ".zap.dart"
        - ".tmp.zap.dart"
        - ".zap.scss"

post_process_builders:
  zap_cleanup:
    import: 'package:zap_dev/builders.dart'
    builder_factory: zapCleanup
    defaults:
      dev_options:
        dev: true
      release_options:
        dev: false
