builders:
  zap_dev:
    import: 'package:zap_dev/builders.dart'
    builder_factories: ["preparing", "api", "zapBuilder"]
    auto_apply: dependents
    build_to: cache
    applies_builders: ["|zap_cleanup"]
    defaults:
      dev_options:
        dev: true
      release_options:
        dev: false
    build_extensions:
      ".zap":
        - ".zap.dart"
        - ".tmp.zap.dart"
        - ".zap.scss"

  sass:
    import: 'package:zap_dev/builders.dart'
    builder_factories: ["sass"]
    build_extensions:
      ".scss": [".css", ".css.map"]
      ".sass": [".css", ".css.map"]
    auto_apply: dependents
    build_to: cache
    applies_builders: ["|zap_cleanup"]
    defaults:
      dev_options:
        style: expanded
        source_maps: true
      release_options:
        style: compressed
        source_maps: false

post_process_builders:
  zap_cleanup:
    import: 'package:zap_dev/builders.dart'
    builder_factory: zapCleanup
    defaults:
      dev_options:
        dev: true
      release_options:
        dev: false
