builders:
  zap_dev:
    import: 'package:zap_dev/builders.dart'
    builder_factories: ["preparing", "api", "zapBuilder"]
    auto_apply: dependents
    build_to: cache
    applies_builders: ["|zap_cleanup"]
    defaults:
      dev_options:
        dev: true
      release_options:
        dev: false
    build_extensions:
      ".zap":
        - ".zap.dart"
        - ".zap.tmp.dart"
        - ".zap.tmp.css"

  aggregate_styles:
    import: 'package:zap_dev/builders.dart'
    builder_factories: ["aggregateCss"]
    auto_apply: root_package
    build_to: cache
    required_inputs: [".css"]
    build_extensions: {"lib/$lib$": ["web/main.css"]}

post_process_builders:
  zap_cleanup:
    import: 'package:zap_dev/builders.dart'
    builder_factory: zapCleanup
