name: zap_dev
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  analyzer: ^2.7.0
  build: ^2.1.1
  collection: ^1.15.0
  csslib: ^0.17.1
  dart_style: ^2.2.0
  path: ^1.8.0
  recase: ^4.0.0
  # We're importing internal sass code, implement sealed interfaces and do other
  # shady things... We're likely to be broken by something that sass wouldn't
  # consider breaking, so let's pin the version here. Users aren't likely to import
  # sass so it's probably fine?
  sass_api: 1.0.0-beta.23
  sass: 1.45.0
  source_span: ^1.8.1
  stack_trace: ^1.10.0
  zap:

dev_dependencies:
  charcode: ^1.3.1
  lints: ^1.0.0
  test: ^1.16.0

dependency_overrides:
  zap:
    path: ../zap
