name: material_zap
description: Port of material web components to zap
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  zap:
  zap_dev:

dev_dependencies:
  build_runner: ^2.1.7

dependency_overrides:
  zap:
    path: ../zap
  zap_dev:
    path: ../zap_dev
