builders:
  index_samples:
    build_to: cache
    import: 'tool/index_examples.dart'
    builder_factories: ["IndexExamples.new"]
    build_extensions: {'.dart': ['json']}

targets:
  $default:
    sources:
      - "lib/**"
      - "pages/**"
      - "templates/**"
      - "web/**"
      - "tool/**"
      - "$package$"
      - "pubspec.yaml"
      - "theme.yaml"
      - "website.yaml"
    builders:
      # Use the sass builder that comes with zap_dev, it's more efficient.
      built_site|sass_builder:
        enabled: false
      "|index_samples":
        enabled: true
