name: zap
description: Zap is a reactive web framework built on Dart. By compiling HTML-like files to Dart components, Zap makes it easy to write efficient web apps.
version: 0.2.0
homepage: https://simonbinder.eu/zap/

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  js: ^0.6.3
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.1.5
  build_test: ^2.1.4
  build_web_compilers: ^4.0.3
  extra_pedantic: ^3.0.0
  test: ^1.16.0
  zap_dev:

dependency_overrides:
  zap_dev:
    path: ../zap_dev
