name: zap
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.3 <3.0.0'

dependencies:
  meta: ^1.7.0

dev_dependencies:
  lints: ^1.0.0
  build_test: ^2.1.4
  build_runner: ^2.1.5
  test: ^1.16.0
  zap_dev:

dependency_overrides:
  zap_dev:
    path: ../zap_dev
