name: zap
description: A reactive web framework built on Dart.
version: 0.1.0
homepage: https://simonbinder.eu/zap/

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  js: ^0.6.3
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.1.5
  build_test: ^2.1.4
  build_web_compilers: ^3.2.1
  extra_pedantic: ^1.5.0
  test: ^1.16.0
  zap_dev:

dependency_overrides:
  zap_dev:
    path: ../zap_dev
