name: seven_guis
version: 1.0.0

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  zap:

dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^3.2.0
  lints: ^1.0.0
  zap_dev:

dependency_overrides:
  zap:
    path: ../../zap
  zap_dev:
    path: ../../zap_dev
