name: example
description: Demo of using riverpod and zap for a simple todo app.
publish_to: none

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  riverpod: ^2.0.0-0
  uuid: ^3.0.5
  picocss:
    hosted: https://simonbinder.eu
    version: ^1.1.4

  riverpod_zap:
  zap:

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^4.0.0
  lints: ^2.1.0
  sass_builder: ^2.2.1
  zap_dev:

dependency_overrides:
  zap:
    path: ../../zap
  zap_dev:
    path: ../../zap_dev
  riverpod_zap:
    path: ../
